# Generated by Django 5.0.4 on 2024-05-07 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorModelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('codigo_licencia', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=20)),
            ],
            options={
                'db_table': 'conductores',
            },
        ),
        migrations.CreateModel(
            name='InspectorModelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=20)),
            ],
            options={
                'db_table': 'inspectores',
            },
        ),
        migrations.CreateModel(
            name='VehiculoModelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('clase', models.CharField(max_length=50)),
                ('anio_fabricacion', models.IntegerField()),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='ActaModelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=200)),
                ('hora', models.TimeField()),
                ('observaciones', models.TextField()),
                ('calificacion', models.CharField(choices=[('Leve', 'Leve'), ('Grave', 'Grave'), ('Muy Grave', 'Muy Grave')], max_length=20)),
                ('sancion', models.TextField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Concluido', 'Concluido')], max_length=20)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infracciones.conductormodelo')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infracciones.inspectormodelo')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infracciones.vehiculomodelo')),
            ],
            options={
                'db_table': 'actas',
            },
        ),
    ]
