# Generated by Django 5.0.4 on 2024-05-24 01:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infracciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductormodelo',
            name='foto',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='inspectormodelo',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto'),
        ),
    ]
