from django.urls import path
from .views import (
    UsuarioView,
    UsuarioCreateView,
    UsuarioUpdateView,
    UsuarioDeleteView,
    IspectorView,
    InspectorCreateView,
    InspectorUpdateView,
    InspectorDeleteView,
    ConductorView,
    ConductorCreateView,
    ConductorUpdateView,
    ConductorDeleteView,
    VehiculoView,
    VehiculoCreateView,
    VehiculoUpdateView,
    VehiculoDeleteView,
    ActaView,
    ActaCreateView,
    ActaUpdateView,
    ActaDeleteView,
)

urlpatterns = [
    path('usuarios/all', UsuarioView.as_view()),
    path('inspectores/all', IspectorView.as_view()),
    path('conductores/all', ConductorView.as_view()),
    path('vehiculos/all', VehiculoView.as_view()),
    path('actas/all', ActaView.as_view()),
    path('usuarios/create', UsuarioCreateView.as_view()),
    path('inspectores/create', InspectorCreateView.as_view()),
    path('conductores/create', ConductorCreateView.as_view()),
    path('vehiculos/create', VehiculoCreateView.as_view()),
    path('actas/create', ActaCreateView.as_view()),
    path('usuarios/update/<int:pk>', UsuarioUpdateView.as_view()),
    path('inspectores/update/<int:pk>', InspectorUpdateView.as_view()),
    path('conductores/update/<int:pk>', ConductorUpdateView.as_view()),
    path('vehiculos/update/<int:pk>', VehiculoUpdateView.as_view()),
    path('actas/update/<int:pk>', ActaUpdateView.as_view()),
    path('usuarios/delete/<int:pk>', UsuarioDeleteView.as_view()),
    path('inspectores/delete/<int:pk>', InspectorDeleteView.as_view()),
    path('conductores/delete/<int:pk>', ConductorDeleteView.as_view()),
    path('vehiculos/delete/<int:pk>', VehiculoDeleteView.as_view()),
    path('actas/delete/<int:pk>', ActaDeleteView.as_view()),
]